In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report,ConfusionMatrixDisplay

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/student performance/Student_performance_data _.csv')

In [4]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [5]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

In [6]:
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [7]:
x = df
y = df.iloc[:,8] #extract the 9th column
y

0       2
1       1
2       2
3       3
4       3
       ..
2387    4
2388    4
2389    2
2390    2
2391    2
Name: ParentalSupport, Length: 2392, dtype: int64

Data normalization

In [8]:
from imblearn.over_sampling import RandomOverSampler
sm = RandomOverSampler()
x,y = sm.fit_resample(x,y)

train_test_split function = splits arrays or matices into random train and test subsets


parameters x = the feature matrix (input variables)
parameters y = the target vector (output variable)


test_size=0.3 = 30% dataset will be allocated to the test set and 70% will be used for training set


random_state=4 = guarantee that the split will be the same every time you run the code


X_train = The training set feature matrix

X_test = The test set feature matrix

y_train = The training set target vector

y_test = The test set target vector

In [9]:
#splitting to test and train data
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

KNN (K-Nearest Neighbors) assumes that similar data points exist close to each other in a given space. Therefore, our task is to find the k closest points to the data point we want to classify or predict

In [10]:
#kneighbors
knn1=KNeighborsClassifier(algorithm='auto',n_neighbors=9,weights='distance')
knn1.fit(X_train,y_train)
y_pred1=knn1.predict(X_test)
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.67      0.92      0.78       238
           1       0.62      0.54      0.58       234
           2       0.32      0.21      0.26       192
           3       0.47      0.28      0.35       213
           4       0.66      0.92      0.77       233

    accuracy                           0.59      1110
   macro avg       0.55      0.57      0.55      1110
weighted avg       0.56      0.59      0.56      1110

Support Vector Machine (SVM) aims to find a hyperplane that separates data points. This hyperplane divides the space into different regions, where each region contains data points of a specific class

In [11]:
#supportvector
sv=SVC(C=10, gamma =1, kernel= 'rbf')
sv.fit(X_train,y_train)
y_pred2=sv.predict(X_test)
y_pred2
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       1.00      0.90      0.95       238
           1       1.00      0.37      0.54       234
           2       0.32      0.99      0.49       192
           3       0.94      0.08      0.14       213
           4       1.00      0.87      0.93       233

    accuracy                           0.64      1110
   macro avg       0.85      0.64      0.61      1110
weighted avg       0.87      0.64      0.62      1110

Random Forest builds multiple decision trees, each trained on different subsets of the data. The final prediction is made based on a voting mechanism across all the decision trees

In [12]:
#randomforest
rf=RandomForestClassifier(criterion= 'entropy', max_depth= None, min_samples_leaf= 1, min_samples_split= 4,n_estimators= 200)
rf.fit(X_train,y_train)
y_pred4=rf.predict(X_test)
y_pred4
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       238
           1       1.00      1.00      1.00       234
           2       1.00      1.00      1.00       192
           3       1.00      1.00      1.00       213
           4       1.00      1.00      1.00       233

    accuracy                           1.00      1110
   macro avg       1.00      1.00      1.00      1110
weighted avg       1.00      1.00      1.00      1110

In [13]:
#decisiontree
rf=DecisionTreeClassifier(criterion= 'entropy', max_depth= None, min_samples_leaf= 1, min_samples_split= 4)
rf.fit(X_train,y_train)
y_pred4=rf.predict(X_test)
y_pred4
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       238
           1       1.00      1.00      1.00       234
           2       1.00      1.00      1.00       192
           3       1.00      1.00      1.00       213
           4       1.00      1.00      1.00       233

    accuracy                           1.00      1110
   macro avg       1.00      1.00      1.00      1110
weighted avg       1.00      1.00      1.00      1110

XGBoost (Extreme Gradient Boosting) is a machine learning technique used to minimize errors during predictive data analysis. It offers fast learning speed and high performance

In [14]:
#xgboost
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred7=xgb.predict(X_test)
y_pred7
print(classification_report(y_test,y_pred7))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       238
           1       1.00      1.00      1.00       234
           2       1.00      1.00      1.00       192
           3       1.00      1.00      1.00       213
           4       1.00      1.00      1.00       233

    accuracy                           1.00      1110
   macro avg       1.00      1.00      1.00      1110
weighted avg       1.00      1.00      1.00      1110